[2020-08-01 10:18:57,953] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 10:19:10,464] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 10:19:10,690] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/js/echarts.min.js HTTP/1.1" 304 0
[2020-08-01 10:19:13,859] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 5209
[2020-08-01 10:19:14,043] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /api/echarts/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\views.py", line 247, in echarts_data
    for j in less_list:
UnboundLocalError: local variable 'less_list' referenced before assignment
[2020-08-01 10:19:14,047] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/pass_stats/ HTTP/1.1" 200 38
[2020-08-01 10:19:14,060] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/echarts/ HTTP/1.1" 500 145
[2020-08-01 10:19:26,678] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 10:19:34,289] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 3101
[2020-08-01 10:19:34,345] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/css/run_test.css HTTP/1.1" 200 634
[2020-08-01 10:20:15,825] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 5209
[2020-08-01 10:20:15,976] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /api/echarts/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\views.py", line 247, in echarts_data
    for j in less_list:
UnboundLocalError: local variable 'less_list' referenced before assignment
[2020-08-01 10:20:15,981] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/echarts/ HTTP/1.1" 500 145
[2020-08-01 10:20:15,984] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/pass_stats/ HTTP/1.1" 200 38
[2020-08-01 10:20:18,597] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 3101
[2020-08-01 10:20:28,703] [autotest_view.py:102] [autotest_view:run_test] [INFO]- 测试完成！ 测试结果集合为:{'filename': 'test_report20200801101954', 'result': {'testAll': 42, 'testPass': 36, 'testFail': 6, 'testError': 0}}
[2020-08-01 10:20:59,451] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 3101
[2020-08-01 10:21:01,134] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 5921
[2020-08-01 10:21:01,300] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /api/echarts/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\views.py", line 247, in echarts_data
    for j in less_list:
UnboundLocalError: local variable 'less_list' referenced before assignment
[2020-08-01 10:21:01,300] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/pass_stats/ HTTP/1.1" 200 65
[2020-08-01 10:21:01,302] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/echarts/ HTTP/1.1" 500 145
[2020-08-01 10:21:13,951] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /test_report/test_report20200801101954 HTTP/1.1" 200 13129251
[2020-08-01 10:21:49,686] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 3101
[2020-08-01 10:22:22,386] [autotest_view.py:102] [autotest_view:run_test] [INFO]- 测试完成！ 测试结果集合为:{'filename': 'test_report20200801102153', 'result': {'testAll': 42, 'testPass': 31, 'testFail': 11, 'testError': 0}}
[2020-08-01 10:22:23,069] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/?csrfmiddlewaretoken=CSKkfD6HHVT70EqjR1FB4JxtnuYpXjggEWkxD2TjjC4nJE7GfMqOy4tAErkzcWOL&test_type=Nec&envId=4&project=yyting-apps-api HTTP/1.1" 200 99
[2020-08-01 10:22:36,706] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 3101
[2020-08-01 10:22:38,031] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 6631
[2020-08-01 10:22:38,160] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/pass_stats/ HTTP/1.1" 200 96
[2020-08-01 10:22:38,168] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 60
[2020-08-01 10:32:34,149] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\templates\admin\platform\settlement\get_CurrentTime.py changed, reloading.
[2020-08-01 10:32:35,140] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 10:33:25,223] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\templates\admin\platform\settlement\get_CurrentTime.py changed, reloading.
[2020-08-01 10:33:26,214] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 10:36:00,987] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\templates\admin\platform\settlement\get_CurrentTime.py changed, reloading.
[2020-08-01 10:36:01,966] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 10:36:15,044] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 10:36:15,088] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/js/echarts.min.js HTTP/1.1" 304 0
[2020-08-01 10:36:18,891] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 10:36:20,219] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 10:36:20,254] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/css/send_vip.css HTTP/1.1" 304 0
[2020-08-01 10:36:23,462] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 10:36:43,748] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 10:36:44,837] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 10:36:47,670] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 10:36:55,953] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 10:37:03,935] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 10:44:54,084] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\templates\admin\platform\common\Create_Number.py changed, reloading.
[2020-08-01 10:44:55,014] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:19:17,151] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\urls.py changed, reloading.
[2020-08-01 11:19:18,084] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:19:28,545] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:28,545] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:29,134] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:29,134] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:29,749] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:29,750] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:30,483] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 11:19:30,817] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:30,818] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:34,871] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform/month_day
[2020-08-01 11:19:34,872] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /platform/month_day HTTP/1.1" 404 179
[2020-08-01 11:19:40,530] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:40,530] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:41,126] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:41,127] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:41,728] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:41,729] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:42,343] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:19:42,343] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:19:42,773] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day_zhou HTTP/1.1" 200 2110
[2020-08-01 11:19:42,818] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/css/send_vip.css HTTP/1.1" 304 0
[2020-08-01 11:20:00,383] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform/month_day
[2020-08-01 11:20:00,384] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /platform/month_day HTTP/1.1" 404 179
[2020-08-01 11:20:02,355] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day_zhou HTTP/1.1" 200 2110
[2020-08-01 11:20:14,482] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform/month_day
[2020-08-01 11:20:14,482] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /platform/month_day HTTP/1.1" 404 179
[2020-08-01 11:20:24,443] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:20:29,083] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day_zhou HTTP/1.1" 200 2115
[2020-08-01 11:20:31,457] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day_zhou HTTP/1.1" 200 2244
[2020-08-01 11:20:57,180] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\urls.py changed, reloading.
[2020-08-01 11:20:58,115] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:21:04,996] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform/month_day_zhou
[2020-08-01 11:21:04,997] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /platform/month_day_zhou HTTP/1.1" 404 179
[2020-08-01 11:21:08,464] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:21:08,464] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:21:08,878] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 11:22:06,281] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\MyPro1\urls.py changed, reloading.
[2020-08-01 11:22:07,276] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:22:11,318] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform/month_day
[2020-08-01 11:22:11,318] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /platform/month_day HTTP/1.1" 404 179
[2020-08-01 11:22:15,017] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:22:15,018] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:22:15,615] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:22:15,616] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:22:16,009] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform1/month_day HTTP/1.1" 200 2110
[2020-08-01 11:22:26,145] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\MyPro1\urls.py changed, reloading.
[2020-08-01 11:22:27,070] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:22:40,213] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:22:48,441] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform1/month_day
[2020-08-01 11:22:48,442] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /platform1/month_day HTTP/1.1" 404 179
[2020-08-01 11:22:52,106] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:22:52,106] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:22:52,710] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 11:22:52,710] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 11:22:53,149] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 11:22:56,193] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 11:22:57,618] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 11:23:02,305] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 11:23:04,904] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 11:27:58,360] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 11:28:09,989] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 11:28:50,491] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/month_day HTTP/1.1" 200 2239
[2020-08-01 11:40:35,568] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 11:40:36,604] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:40:49,787] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /add_Subtracts_activity/ HTTP/1.1" 200 2882
[2020-08-01 11:40:54,719] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 11:41:01,695] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/add_copyright_partner HTTP/1.1" 200 3426
[2020-08-01 11:46:06,501] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 11:46:07,439] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:47:21,947] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 11:47:22,871] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 11:48:02,338] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 11:48:03,312] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 12:04:26,571] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 12:04:27,539] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:12:19,866] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\urls.py changed, reloading.
[2020-08-01 14:12:20,810] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:12:37,915] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:12:51,130] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 14:12:51,131] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 14:12:51,662] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11144
[2020-08-01 14:17:01,025] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:17:09,250] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:17:11,772] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:17:13,508] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:17:44,973] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:17:59,135] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:18:00,516] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/month_day HTTP/1.1" 200 2110
[2020-08-01 14:18:02,453] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:18:04,035] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:18:06,954] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:18:07,893] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:18:14,813] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:18:15,859] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:18:17,997] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:18:18,893] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:22:51,346] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:22:58,711] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:23:00,657] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:23:01,786] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:23:24,454] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:23:25,921] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:24:47,004] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:24:47,938] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:24:48,970] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2041
[2020-08-01 14:26:29,388] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 14:26:30,354] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:26:32,430] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 1913
[2020-08-01 14:27:20,416] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:27:21,391] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:27:22,120] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 1913
[2020-08-01 14:27:32,907] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:27:34,019] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:27:52,541] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 1913
[2020-08-01 14:28:30,037] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 14:28:30,980] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:29:34,793] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:29:35,733] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:29:42,542] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:29:48,637] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2506
[2020-08-01 14:29:54,643] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2642
[2020-08-01 14:30:45,509] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:30:46,437] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:31:24,712] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:31:25,676] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:31:39,176] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2642
[2020-08-01 14:32:14,572] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:32:15,680] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:32:18,256] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:32:23,543] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2641
[2020-08-01 14:32:29,528] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2642
[2020-08-01 14:32:38,947] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:19,265] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:34:20,292] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:34:24,309] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:25,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:26,479] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:26,723] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:26,911] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:27,083] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:27,261] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:34:27,458] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2634
[2020-08-01 14:47:04,226] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:47:05,164] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:47:13,979] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:47:19,184] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:49:05,752] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 14:49:06,697] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:49:14,893] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:43,311] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 14:50:44,280] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 14:50:48,434] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:49,265] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:49,521] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:49,713] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:49,873] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:50,025] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:50,192] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:50,354] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:50:53,326] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:50:55,585] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 14:51:00,323] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 14:51:00,757] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 14:51:00,920] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 14:51:03,264] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:51:09,329] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:51:29,423] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 14:51:49,616] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 14:52:33,494] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 14:52:35,454] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 14:55:14,566] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\MyPro1\settings.py changed, reloading.
[2020-08-01 14:55:15,532] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:00:08,248] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\MyPro1\settings.py changed, reloading.
[2020-08-01 15:00:09,273] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:00:42,756] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\randomNum_views.py changed, reloading.
[2020-08-01 15:00:43,674] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:00:52,210] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:00:57,010] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2619
[2020-08-01 15:01:00,915] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2620
[2020-08-01 15:01:03,768] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 15:15:07,584] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:15:08,507] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:15:15,045] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 15:15:30,143] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 15:15:30,144] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 15:15:30,671] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:15:32,373] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:15:45,261] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 15:15:50,004] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:15:52,186] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:15:53,767] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:16:37,903] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:17:55,884] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:17:57,808] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:18:00,280] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:18:01,815] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:31:19,432] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:38:51,005] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:40:31,366] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:40:33,133] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/add_channel_partner HTTP/1.1" 200 3529
[2020-08-01 15:41:43,836] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:41:44,763] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:41:49,838] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:41:51,726] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:41:52,844] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:41:54,856] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:43:04,121] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:43:06,138] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:43:07,005] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:43:18,455] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:43:22,799] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:44:09,837] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:47:13,973] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:47:14,965] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:47:16,116] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:47:20,034] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:47:22,143] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/randomNum HTTP/1.1" 200 2609
[2020-08-01 15:47:26,086] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 15:47:27,240] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:47:37,111] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:47:38,119] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:48:16,437] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:48:17,399] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:48:18,676] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:48:20,819] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:50:19,462] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:52:18,677] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:52:19,586] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:52:39,637] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:52:44,997] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:52:54,581] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:52:55,529] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:52:59,696] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:53:25,899] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:53:26,826] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 15:53:29,903] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/randomNum HTTP/1.1" 200 2481
[2020-08-01 15:53:37,246] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 15:53:38,161] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 16:01:09,132] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 16:01:52,912] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /items_list/3 HTTP/1.1" 200 354
[2020-08-01 16:02:01,310] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 16:02:05,880] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /items_list/2 HTTP/1.1" 200 514
[2020-08-01 16:02:07,893] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 16:02:10,904] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /items_list/3 HTTP/1.1" 200 354
[2020-08-01 16:02:12,617] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 16:02:22,943] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /items_list/3 HTTP/1.1" 200 354
[2020-08-01 16:07:15,280] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 16:25:57,007] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 3101
[2020-08-01 16:31:56,651] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11418
[2020-08-01 16:31:58,283] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 302 0
[2020-08-01 16:31:58,323] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2210
[2020-08-01 16:31:58,377] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/css/login.css HTTP/1.1" 304 0
[2020-08-01 16:31:58,425] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/img/photos/timg3.jpg HTTP/1.1" 304 0
[2020-08-01 16:32:05,747] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 200 2322
[2020-08-01 16:32:11,852] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /register/ HTTP/1.1" 200 3010
[2020-08-01 16:32:11,930] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/css/register.css HTTP/1.1" 200 613
[2020-08-01 16:32:11,963] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/img/photos/timg.jpg HTTP/1.1" 200 20895
[2020-08-01 16:32:42,841] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /register/ HTTP/1.1" 302 0
[2020-08-01 16:32:42,851] [log.py:228] [log:log_response] [WARNING]- Not Found: /login
[2020-08-01 16:32:42,852] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /login HTTP/1.1" 404 179
[2020-08-01 16:32:45,804] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /register/ HTTP/1.1" 200 3010
[2020-08-01 16:32:47,591] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2210
[2020-08-01 16:32:56,389] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2020-08-01 16:32:56,407] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11421
[2020-08-01 16:33:02,166] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 200 6683
[2020-08-01 16:33:18,856] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11421
[2020-08-01 16:33:21,561] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 200 6683
[2020-08-01 16:33:40,195] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11421
[2020-08-01 17:03:33,787] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:03:34,759] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 17:03:42,885] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:03:43,812] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 17:06:34,487] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:06:35,470] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 17:08:43,614] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:08:44,540] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 17:10:43,290] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:10:44,263] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 17:12:24,306] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:12:25,251] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 17:13:46,657] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 17:13:47,637] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:09:40,350] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\urls.py changed, reloading.
[2020-08-01 18:09:41,377] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:20:03,720] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\urls.py changed, reloading.
[2020-08-01 18:20:04,658] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:20:43,218] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:20:46,599] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11799
[2020-08-01 18:20:51,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /items_list/3 HTTP/1.1" 200 354
[2020-08-01 18:20:55,155] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11799
[2020-08-01 18:21:58,425] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:21:59,670] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11823
[2020-08-01 18:22:32,360] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:22:35,212] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11814
[2020-08-01 18:22:36,524] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:22:36,526] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:22:38,827] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11814
[2020-08-01 18:22:41,287] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:22:41,288] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:25:44,171] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:25:44,172] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:25:56,105] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:25:59,250] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:25:59,252] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:26:01,534] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_config/ HTTP/1.1" 200 6681
[2020-08-01 18:26:10,389] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 18:26:10,390] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 18:26:11,028] [log.py:228] [log:log_response] [WARNING]- Not Found: /platform/
[2020-08-01 18:26:11,029] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /platform/ HTTP/1.1" 404 179
[2020-08-01 18:26:14,701] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 18:26:14,701] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 18:26:15,309] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 18:26:15,310] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 18:26:15,912] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 18:26:15,912] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 18:26:16,527] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-08-01 18:26:16,527] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-08-01 18:26:17,000] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11814
[2020-08-01 18:26:19,090] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:26:19,091] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:26:20,683] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11814
[2020-08-01 18:26:44,307] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:26:44,308] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:26:46,013] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11814
[2020-08-01 18:27:42,921] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:27:42,922] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:30:15,344] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:30:15,345] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:30:53,765] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:30:54,703] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:30:59,278] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:30:59,280] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:33:20,406] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:33:21,326] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:33:30,387] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:33:31,324] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:33:39,489] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 23, in settlement_not_vip
    settlement_form = platform_forms.settlement_not_vip_form(request.POST)
TypeError: settlement_not_vip_form() takes no arguments
[2020-08-01 18:33:39,491] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:34:40,020] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 18:34:40,974] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:34:47,670] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\formsgroup\platform_forms.py changed, reloading.
[2020-08-01 18:34:48,643] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:35:09,546] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/settlement_not_vip HTTP/1.1" 200 3198
[2020-08-01 18:36:22,017] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:36:22,934] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:37:02,416] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:37:03,367] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:37:15,418] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 31, in settlement_not_vip
    settlement_record=Settlement(int(Settlement_Date),int(Settlement_Res_ID),int(Settlement_Partner_ID),int(Settlement_Cooperation_Business)).settlement_partner()
  File "E:\Auto\testplat\login\templates\admin\platform\settlement\Settlement.py", line 131, in settlement_partner
    yaya_list=self.settlement_lr_yaya(2)
  File "E:\Auto\testplat\login\templates\admin\platform\settlement\Settlement.py", line 99, in settlement_lr_yaya
    lr_sum_cash_flow_billing = sum_cash_flow_billing
UnboundLocalError: local variable 'sum_cash_flow_billing' referenced before assignment
[2020-08-01 18:37:15,420] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:40:24,369] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\templates\admin\platform\settlement\Settlement.py changed, reloading.
[2020-08-01 18:40:25,301] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:40:33,122] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:40:34,268] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:41:24,608] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:41:25,575] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:41:29,695] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/settlement_not_vip HTTP/1.1" 200 3198
[2020-08-01 18:41:36,337] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /platform/settlement_not_vip
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\platform_views\settlement_views.py", line 31, in settlement_not_vip
    settlement_record=Settlement1(int(Settlement_Date),int(Settlement_Res_ID),int(Settlement_Partner_ID),int(Settlement_Cooperation_Business)).settlement_partner()
  File "E:\Auto\testplat\login\templates\admin\platform\settlement\Settlement.py", line 131, in settlement_partner
    yaya_list=self.settlement_lr_yaya(2)
  File "E:\Auto\testplat\login\templates\admin\platform\settlement\Settlement.py", line 99, in settlement_lr_yaya
    lr_sum_cash_flow_billing = sum_cash_flow_billing
UnboundLocalError: local variable 'sum_cash_flow_billing' referenced before assignment
[2020-08-01 18:41:36,339] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /platform/settlement_not_vip HTTP/1.1" 500 145
[2020-08-01 18:41:52,560] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:41:53,516] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:42:03,742] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:42:04,735] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:42:18,377] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:42:19,419] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:42:46,216] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:42:47,165] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:43:33,676] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\platform_views\settlement_views.py changed, reloading.
[2020-08-01 18:43:34,629] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-01 18:43:36,267] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /platform/settlement_not_vip HTTP/1.1" 200 3198
[2020-08-01 18:43:38,183] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /platform/settlement_not_vip HTTP/1.1" 200 3619
[2020-08-03 10:57:53,413] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11811
[2020-08-03 10:57:53,443] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/js/echarts.min.js HTTP/1.1" 304 0
[2020-08-03 10:57:56,806] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /add_cases/ HTTP/1.1" 200 3136
[2020-08-03 10:57:59,810] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11811
[2020-08-03 10:58:00,998] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 3686
[2020-08-03 10:58:51,225] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /upload_cases/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\test_view\cases_views.py", line 73, in upload_cases
    f = open(os.path.join(BASE_DIR, File.name), 'wb')
PermissionError: [Errno 13] Permission denied: 'E:\\Auto\\testplat\\login/files\\APIcase_2019.xls'
[2020-08-03 10:58:51,246] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /upload_cases/ HTTP/1.1" 500 145
[2020-08-03 10:59:07,072] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11811
[2020-08-03 10:59:09,482] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2210
[2020-08-03 10:59:09,520] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/css/login.css HTTP/1.1" 200 1121
[2020-08-03 10:59:09,584] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/login/img/photos/timg3.jpg HTTP/1.1" 200 13234
[2020-08-03 10:59:33,962] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 3686
[2020-08-03 10:59:40,750] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /upload_cases/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\test_view\cases_views.py", line 73, in upload_cases
    f = open(os.path.join(BASE_DIR, File.name), 'wb')
PermissionError: [Errno 13] Permission denied: 'E:\\Auto\\testplat\\login/files\\APIcase_2019.xls'
[2020-08-03 10:59:40,759] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /upload_cases/ HTTP/1.1" 500 145
[2020-08-03 11:00:27,322] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /upload_cases/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\test_view\cases_views.py", line 73, in upload_cases
    f = open(os.path.join(BASE_DIR, File.name), 'wb')
PermissionError: [Errno 13] Permission denied: 'E:\\Auto\\testplat\\login/files\\APIcase_2019.xls'
[2020-08-03 11:00:27,324] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /upload_cases/ HTTP/1.1" 500 145
[2020-08-03 11:00:40,821] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 3686
[2020-08-03 11:00:47,298] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /upload_cases/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Auto\testplat\login\viewas\test_view\cases_views.py", line 79, in upload_cases
    data = pd.read_excel(f.name, sheet_name=0)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\excel\_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\excel\_base.py", line 824, in __init__
    self._reader = self._engines[engine](self._io)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\excel\_xlrd.py", line 20, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\compat\_optional.py", line 92, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2020-08-03 11:00:47,303] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /upload_cases/ HTTP/1.1" 500 145
[2020-08-03 11:04:07,664] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 3686
[2020-08-03 11:04:14,994] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_cases/ HTTP/1.1" 302 0
[2020-08-03 11:04:15,145] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_detail/ HTTP/1.1" 200 43276
[2020-08-03 11:05:31,520] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_detail/ HTTP/1.1" 200 43276
[2020-08-03 11:05:33,732] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11811
[2020-08-03 11:05:43,076] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 16461
[2020-08-03 11:07:49,724] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11811
[2020-08-03 11:07:50,889] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11811
[2020-08-03 11:07:52,242] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 16461
[2020-08-03 11:09:01,672] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 16461
[2020-08-03 11:17:37,380] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /cases_pages/1 HTTP/1.1" 200 16461
[2020-08-03 11:19:24,174] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\Auto\testplat\login\viewas\test_view\cases_views.py changed, reloading.
